version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8082:8082"
    depends_on:
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  microservice:
    build:
      context: ./microservice
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker