server:
  port: 8082

spring:
  application:
    name: ratelimiter-example
  cloud:
    gateway:
      routes:
        - id: route1
          uri: http://localhost:8080/hello
          predicates:
            - Path=/hello
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 3
                redis-rate-limiter.burstCapacity: 8
                redis-rate-limiter.requestedTokens: 1
  data:
    redis:
      port: 6379
      host: localhost